/**
 * Pure decision logic for the Senpi runtime plugin (re)install in bootstrap.mjs.
 *
 * Extracted from `installSenpiRuntimePluginIfNeeded` so the wipe/reinstall
 * trigger can be unit-tested in isolation — see the "scope mismatch ⇒ wipe on
 * every boot" failure mode this guards against (fleet-update spec §4.2) and the
 * production incident where hoisted transitive deps never downgraded because the
 * old spec-mismatch path only removed the plugin dir, not the whole tree (§2).
 *
 * Two independent triggers, both compared against what was last recorded on the
 * volume (`cfg.plugins.installs["runtime"]` in STATE_DIR/openclaw.json):
 *
 *   1. Spec change   — recorded `spec` !== configured `SENPI_RUNTIME_NPM_SPEC`.
 *   2. Reinstall nonce — recorded `nonce` !== configured
 *      `SENPI_RUNTIME_REINSTALL_NONCE`, but ONLY when the configured nonce is
 *      non-empty. Absent and empty-string are treated identically and mean
 *      "never force". The nonce is a one-shot latch: the volume records the last
 *      value acted on, so only *inequality* fires — the same value on the next
 *      boot no-ops, and removing the nonce from the env after it was recorded
 *      also no-ops (empty configured nonce never triggers).
 *
 * Every trigger — spec change, nonce change, or a MISSING install record —
 * returns `wipeAndInstall`: the caller wipes the managed npm root artifacts
 * listed in NPM_WIPE_TARGETS (node_modules AND the lockfile/manifest — see
 * below) so transitive deps re-resolve from scratch and can downgrade.
 *
 * The no-record case wipes too because "no record" does NOT imply "clean
 * tree": a volume whose record was lost (old-scope install the path probe
 * misses, corrupted openclaw.json, partial prior failure) still carries the
 * stale lockfile + merged manifest + node_modules, and a plain install on that
 * tree is exactly the lockfile-re-pin failure mode this module exists to
 * prevent. Worse, with no record the nonce comparison can never force, so the
 * fleet nonce lever could not heal such a volume. On a genuinely fresh volume
 * the wipe is rmSync({force: true}) on nonexistent paths — a free no-op.
 *
 * @typedef {Object} InstallRecord
 * @property {boolean} exists  Whether cfg.plugins.installs["runtime"] is present.
 * @property {string} [spec]   Recorded npm spec of the last install.
 * @property {string} [nonce]  Recorded reinstall nonce of the last install.
 *
 * @typedef {Object} InstallEnv
 * @property {string} spec     Configured SENPI_RUNTIME_NPM_SPEC.
 * @property {string} [nonce]  Configured SENPI_RUNTIME_REINSTALL_NONCE.
 *
 * @typedef {Object} InstallDecision
 * @property {"none"|"wipeAndInstall"} action
 * @property {string} reason   Human-readable, safe to log.
 */

/**
 * Entries (relative to STATE_DIR/npm) a `wipeAndInstall` must remove so the
 * follow-up `openclaw plugins install` re-resolves dependencies from scratch.
 *
 * Why all three — verified against OpenClaw source at tag v2026.5.7 (the
 * Dockerfile-pinned build):
 *
 *   - `node_modules`: the installed tree itself (incl. node_modules/.package-lock.json).
 *   - `package-lock.json`: FATAL if it survives. The managed install is a plain
 *     `npm install` run in STATE_DIR/npm with the lockfile HONORED —
 *     `src/plugins/install.ts:1375-1398` passes `packageLock: true`, which
 *     `src/infra/safe-package-install.ts:34-35` maps to
 *     `npm_config_package_lock: "true"` (+ `npm_config_save: "true"`). With
 *     node_modules wiped but the lock intact, npm rebuilds the exact locked
 *     tree — stale transitive deps re-pin and the wipe accomplishes nothing.
 *   - `package.json`: the managed-root manifest. `upsertManagedNpmRootDependency`
 *     (`src/infra/npm-managed-root.ts:184-224`) MERGES dependencies
 *     (`{...existing, [name]: spec}`), so a stale entry under an old scope
 *     (e.g. `@senpi/runtime`) survives the upsert and npm reinstalls it
 *     alongside the new scope.
 *
 * All three are regenerated by openclaw on the next install — nothing here is
 * required-but-not-regenerated:
 *   - package.json: `readManagedNpmRootManifest` returns {} on ENOENT
 *     (`npm-managed-root.ts:103-113`); `upsertManagedNpmRootDependency` mkdirs
 *     STATE_DIR/npm and rewrites the manifest BEFORE npm runs
 *     (`install.ts:1366`).
 *   - package-lock.json: rewritten by `npm install` itself (package-lock + save
 *     enabled); the post-install verification (`install.ts:1424-1442`) reads
 *     the freshly written lock, and `repairManagedNpmRootOpenClawPeer`
 *     tolerates a missing one (`npm-managed-root.ts:288-312`).
 *   - node_modules: created by npm install.
 */
export const NPM_WIPE_TARGETS = Object.freeze([
  "node_modules",
  "package-lock.json",
  "package.json",
]);

/**
 * Normalize a nonce for comparison: absent (null/undefined) and empty/whitespace
 * are all collapsed to "" so they compare equal. Trimming also defends against a
 * stray newline injected by the env layer masquerading as a "new" value.
 *
 * @param {unknown} v
 * @returns {string}
 */
export function normalizeNonce(v) {
  if (v === null || v === undefined) return "";
  return String(v).trim();
}

/**
 * Decide what the runtime installer should do given the recorded install state
 * and the configured environment. Pure: no I/O, no env reads.
 *
 * @param {{ record?: InstallRecord|null, env: InstallEnv }} args
 * @returns {InstallDecision}
 */
export function decideRuntimeInstall({ record, env } = {}) {
  const configuredSpec = env?.spec;
  const configuredNonce = normalizeNonce(env?.nonce);
  const recordedNonce = normalizeNonce(record?.nonce);

  // A configured nonce only forces when it's non-empty AND differs from what was
  // recorded. Empty configured nonce = never force (removing it after a record
  // was written no-ops).
  const nonceForces = configuredNonce !== "" && configuredNonce !== recordedNonce;

  // No recorded install. "No record" does NOT imply "clean tree" — a dirty
  // volume that lost its record (old-scope install the path probe misses,
  // corrupted openclaw.json, partial prior failure) still carries the stale
  // lockfile/manifest/node_modules, and with no record the nonce lever can
  // never force a heal. Wipe to guarantee a clean tree; on genuinely fresh
  // volumes the rm is force:true on nonexistent paths — a free no-op.
  if (!record || !record.exists) {
    return {
      action: "wipeAndInstall",
      reason:
        "no install record — wiping managed npm root to guarantee a clean tree " +
        "(no-op on fresh volumes)",
    };
  }

  // Spec change takes precedence — the recorded install is for a different spec.
  if (record.spec !== configuredSpec) {
    return {
      action: "wipeAndInstall",
      reason:
        `spec changed (recorded=${JSON.stringify(record.spec)} ` +
        `configured=${JSON.stringify(configuredSpec)})`,
    };
  }

  if (nonceForces) {
    return {
      action: "wipeAndInstall",
      reason:
        `reinstall nonce changed (recorded=${JSON.stringify(recordedNonce)} ` +
        `configured=${JSON.stringify(configuredNonce)})`,
    };
  }

  return {
    action: "none",
    reason: "spec and nonce match recorded install",
  };
}
